steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/node-web-app:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mydeployment', 'mynode=gcr.io/sit737-23t1-shetty-7813b9c/node-web-app:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=helloworld-cluster'